export enum LocalStorageKeys {
    AuthToken = "token",
    SessionToken = "sessionToken",
    Profile = "profile",
    Restaurant = "restaurant",
    AccountRefId = "accountRefId",
    IsRegisterRestuarant = "isRegisterRestuarant",
    DeviceToken = "deviceToken",
    IsRestuarantCheckListLoaded = "isRestuarantCheckListLoaded",
    BusinessRefId = "businessRefId",
    NativeAppsInfo = "nativeAppsInfo",
    KdsSettingsUpdated = "kdsSettingsUpdated",
    BrandColor = "brandColor",
    EnterpriseBrandColor = "enterpriseBrandColor",
    OverViewSelectedDateFilter = "overViewSelectedDateFilter",
    FirstTimeSocailMediAuth = "firstTimeSocailMediAuth",
    isEnterpriseView = "isEnterpriseView",
    hasLoggedIn = "hasLoggedIn",
}
